Update docker-dist-tests.yml
Signed-off-by: Air <88528265+air3ijai@users.noreply.github.com>

diff --git a/.github/workflows/docker-dist-tests.yml b/.github/workflows/docker-dist-tests.yml
--- a/.github/workflows/docker-dist-tests.yml
+++ b/.github/workflows/docker-dist-tests.yml
@@ -25,26 +25,35 @@ on:
         default: false
 
 
+env:
+  run_release_tests: ${{ inputs.run_release_tests }}
+
+
 jobs:
-  compute-inputs:
-    name: Compute inputs
-    runs-on: ubuntu-latest
-    outputs:
-      run_release_tests: ${{ steps.compute.outputs.run_release_tests }}
-    steps:
-      - name: Compute inputs
-        id: compute
-        run: |
-          echo "run_release_tests=${{ inputs.run_release_tests }}" >> "$GITHUB_OUTPUT"
+  # compute-inputs:
+  #   name: Compute inputs
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     run_release_tests: ${{ steps.compute.outputs.run_release_tests }}
+  #   steps:
+  #     - name: Compute inputs
+  #       id: compute
+  #       run: |
+  #         echo "run_release_tests=${{ inputs.run_release_tests }}" >> "$GITHUB_OUTPUT"
+  #         [[ -n "${{ inputs.run_release_tests }}" ]] && echo "TESTS_CLEANUP=${{ inputs.tests_cleanup }}" >>"$GITHUB_ENV" || echo "TESTS_CLEANUP=${{ env.TESTS_CLEANUP }}" >>"$GITHUB_ENV"
+
 
   build-and-push:
     name: Build and Push
-    needs: compute-inputs
+    # needs: compute-inputs
+    env:
+      run_release_tests: ${{ inputs.run_release_tests }}
     uses: ./.github/workflows/docker-reusable.yml
     with:
       nimflags: '-d:disableMarchNative -d:codex_enable_api_debug_peers=true -d:codex_enable_proof_failures=true -d:codex_enable_log_counter=true -d:verify_circuit=true'
       nat_ip_auto: true
       tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
       tag_suffix: dist-tests
-      run_release_tests: ${{ needs.compute-inputs.outputs.run_release_tests }}
+      # run_release_tests: ${{ needs.compute-inputs.outputs.run_release_tests }}
+      run_release_tests: ${{ fromJSON(env.run_release_tests }}
     secrets: inherit
